language: ruby
branches:
  only: master
rvm:
- '2.2'
cache: bundler
env:
  global:
  - secure: VlCMS54A5ElzarkAcbFH9kLEe5IlmxAXWweLtyUNWkqSaWbeIN9j/F/YiajvyoZ7yODvFbvK4jVgRxTGPoySSns+NyPhTfVoGjyfD8SO4WaDOS3Llj4ZevakGjyBR83mI1abGjUmXZa58wv59GWW4KDndsSEC673hwl1LP4hm+XSIUYvpGELkJ+/nzB4046vEVfN0gycJ8T6rZ1sX8Uhx5Pz9AKmC6wE//ypB3sfE2BZBNwRNWcVVVQGlErtT9wJehqOIAP2EebfIwbNSnbVX10tcAc/sxNdiFGA5k3o2CmUtwxXyT4O0VxAHDGFoJdtFE8Upr+1KFP3XyChx5dLHN0UeMpQqhucXho7kE6Mf4cu8Tfv2kfrtTx+OedxGY8cqfDwWW5RdsBGA4H7bN1H9cMekkr6nuLhbwbEDkaxnopqT4q2CBk6dtWBw8Q6awPuPj6Emt2LFjClqDN+OFBfqZHJgIN0hKsVLwTgNBF1KyIKTmxI47OwBEW+EmRjPLK6A/jZXEF0aQYR5j2Jae8nQ56lpLaS4BrUeUva1o3migfllOtXgQZn3lR2X9oxHfxAqbAFfyNcVoSwFUbfB/5Zru0XBMEU0NJOAp5Sa1e74EZ/HtcuI6qSLEAEGR24hUoeyG2qW8zd3hIzZvIIykDxgBUPm3+yl1y7R0zaIgMg3/c=
  - secure: V+7v5Et1db3VktgWumWZFYKHfnjyYxZ3rMEAa3lJTprsuedWhs2m/UyLRbYEaCwiu+OkudWlWyiEiZz/IR8h7AGrh16I+GNdL5riHByoG6lLXvoosdU9xB5gp/kGdaJvQtXaCs9PNVrcE9bUQFPF2iSfvveyvUW7PjYqc9KX6DIUDyg/T4NOrEac8rbq4I6VGWTIH2e2W/sowX7XLNk4OE5DG6HVBsIv1TsYRY1DSAUsMPjJjan3yQVLsXt9shs2LHLBgaVfvqthjAIhofY33EFCnWQORd2I6JLMOG2NOjOJQnwO+ifpgLsLjI+9HIqQUIS1Yjr07aAHp2zMdMYJSLHZl3nJuXIFo7Y+KCSc6J7mX931LyrXxqBIxRut7ne8BuSmNFiZnw3ZWYLG92oQxDiO7QpzfxmfVzxcUXcp7AKUoszIl7whnDCVO06mp65lQ+YMMH75PjcSg3zqj0ymkWS8kUhQTrfO4r9pftlVgMmYz5gebY1TbKcLVjOxCbEfNdeBuSFMRWk2wOxnw0SfWMKRWusaApO4c1tHxhvVnVLiB6wkMzVPH5adII2EusSs7I5/hQmioeapODKZE8JCxTZAiOzNqMxltRR81NTzPK2NyHa1wENZHe8dSp2gOV5z77TFCKvl5hJKjM2QUFAiqXisEX1xjw7XLF77YFxN7ck=
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- Rakefile
- s3_website.yml
url: https://mccardle.io
script:
- echo "Executing bundler..."
after_script:
- bundle exec rake deploy
