language: ruby
branches:
  only: master
rvm:
- '2.2'
cache: bundler
env:
  global:
  - secure: ok1rlk/va1ecrQe04gqPX5LPU/5R4MUGNc2SLxxZUibyYaJE9O64HuvKUNDg+eozvBpGtMpf4eDAopY6mLZBAHdgQdAtGIzGkAyeZLQfWUH3keOdE8UMN2tRGu6MeJP0E2z4qacJhL2WOPxqd6+UC0M5M/wI10edg7CFIbMpUVC7Py21/i3GePfouCqWzP8JFclDJviOjpY0Ns34gJ/s0SXigWNVbryw1hUXOo3ap4NOAox4FcRUaZ+XIlvOOLkFX9W/5P+L6VqShTMsLy/d2mcIdlE8Cvig440LaUpspx/kxbTyyZ8hwrXTXddUQXeGxLJJLl8NhAVa2+Kf4L47bKUGQs2Tulk/V0I0XuHT2aWQ5p+jxPB1R8GB8DueWXUg9EcwfBnl3OGHtGdzAb1vv4NVLx8Lgl9FeIGWL38sCcyybTNla4SbXrSYQPiM24qgyIANjqFhtyIdvk6npx7j/v8W6kCEqRMcWDrgiBWVpcq8hVmDm4HYYuV/0AEKKkNAw1iwQxlYf4BIOyVSjQ3X1UNalgEdY+djHjKXtIyE8LxUB1AcQ6zla6No7c/ImDG6D+GIYScASoNOT7yt5We2tT/mlcKSFPSKOJd6Pn+tGc1nP5X/wkLYUCnMRlN4Gld7WRHLgaAqUXNvlXv6TMkQDqn+5anxmx8UiBG3QjR0WbM=
  - secure: fgyHieJYczRdowDz+iX8AnkHxKumHhkdXmNZ7Eu09RBPwkKZJ2Ws+Xv/IkPpu3uUeKDnCMe/xzP+rVu1lRpctvAcz/iXTmS+znoXLmeT8UTYqwKcqJSgfpkk0+lDdGyYHfTrKyAX0Uht10kzyrxhalINlPLUDut/O5g1tgfJfvFANXlA/WxiMmKniHbxnTbWKyPJtEFRtpxKUakt3K7QMR6u+AQHftX7z+AZJX+1BLCIstk58uQvFbrFw6trA96EJ5s8kgXfeIHvEUT6YxJSpMOA8GPvMVuNcEI5KyfscWKVKxnaM6kM+B3S9pyTTZjJ2LNjnjMNH0jBNCrGQsJeUjbF64K1wer6tWV0TYUFBPn6n+EQR0VFYBooiRIoykhrIsz1OdxZO/dFqXVMds2mO9sDFhoQPVnq8o9LSuxtt6cLb8lzpB60Qg8taQloDi7FbQopW5qOF9ieEowhqHWghaDK1tTGBHtEpEbNEKrFg42jRkn0zWKWsB4CMrsRLOpsCQzVqTgUKeZKOBgPzfXeoJb2nQY4tIfVMjqO36rilbqhQe/TCkXRs/1S68a+E8vrKqTnzMsOIIk9DKpvmudubQd8UY9dA+rp0e3mqGr+525yX1XKmdlt5UkikbtluxO+x7QyOf6ubBpnrHVqafVAfyMrHisZ7uuQTemOF8bFSDU=
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- Rakefile
- s3_website.yml
url: https://mccardle.io
script:
- echo "Executing bundler..."
after_script:
- bundle exec rake deploy
