language: ruby
branches:
  only: master
rvm:
- '2.2'
cache: bundler
env:
  global:
  - secure: nshTNGmctVDQks9pvYMBkf4ogkr0mUPCkEw5izHzJO4MKRsB/y9JAZiqlhDF90a4rlQt6ESp3Kpyy0osQY/sZItDruMP2gVeu6SqFMIyXUQxDWFsPjhVx7be3vEX7SVEojpBt/M4Ls3/poVfxftyYdTAHNDTBjbSPpO0tnQobO1wd3hZX/F4hH9s6Cqwff1xqpJ+PJM4sJdNhzezwtHOtJblNL4YZoELfbZlB12Ynon2UJH4cFzvXAMAPgzrQ60BMxZlNFxJM+C7/MddNCL57CJet7sZM/90JAYypweflPMwy1eREijigPOQHQ2yflgwzmkNgkRoK8zdozdS8VcuXFlQJyfOxpoV6JUnM5Dz0xWd/MUWkAKm09H4N12mUOENHdy6x7IWHZh9cSkr1ipd2RRiTfkc4D4ra7vbRZesDkw+ghV3FIxSNqt4KEHG+huoIHkiTigOuaxlwIgI8EcceqQq0w9iPTWf6qetU1025hoQCL4KxwHacY8mCZJxPEuAUSCFUgnL8qMyp1hD+W01KgPK8HI+SpYh2RUSGc3OryCMv7N33YnSvBpmGwEkyxg1w3belxDzYgkHKufCFM8JcdhpSEi9fASKR0eiyTFyw2qFmJkKhIxi46BvuoBTTCmnNBfp0boV2utu+aAIQwll6zkeIcWqjXqOwfmCBWmCCRY=
  - secure: TuUZ/K5kTSHdAXC1iD2poPK6Cjyo5em4whkrSdm89Fe2lUEjNiOfS2hFYyY4SIKJqYo0r9o9NiCNhg94yzXBDQPvWxClB38d+NaSOE8xHXDfad7UZD+5nU7R8DU7u7DeTHDjiQikVseiyxyEmH09KADpLJbptRKhPy1j6NeR9vtKKeePpuHfeC+vOO7KahD+h7k0JmGrY9/X2E6l7nmOFJmh+wKwJQA9bKDZ0jshhCaO7jb7qO9v8RHPyPDbZSK+PKes5HqW/2DblE35lRuJo+ZYx0lsNINKYC4628Kxurk18vjhtY1l7s1ttFkqpyg2CQIXvvPxdOj6alYe1bIPdjJRM3xJdiDOVBpgUY/3Hg7v0Wx3p4sQJyOOBnHX5wH+FAuu7MWxmfWVTFyaEqJjOiw/sPiiyKErqLLCz7kHMobuNlrPYWBBBDCeAQHZlNuh0ZclNHwJKVy9q/S239ToQSANejAjdTQD+85zB7Rk4fQoeHDINnqy3mlRLVCy8n8UNXWFb78jBzdIeidq/uGIK+7rE5M7JnYmBv1Fx3l4InjMVKaiRGKGS/iEoLlsRtzY2wKofeLql4giT9OydfqwJUXkdjzaGRk/a1HcOXMn1KFGi3xiUO5PM2RK3YJDO1pkOc92k43W5t3+QWSsli+n3RpYRZNNxnl7vtN0ktwLxjk=
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- "*.sublime-*"
- lib
- vendor
- Rakefile
- s3_website.yml
url: https://mccardle.io
script:
- echo "Executing bundler..."
after_script:
- bundle exec rake deploy
