# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rob McCardle. Creative Technology Director, Buckinghamshire UK
email: rob@mccardle.io
description: > # this means to ignore newlines until "baseurl:"
  Rob McCardle. Creative Technology Director, Buckinghamshire UK
baseurl: "" # the subpath of your site, e.g. /blog
url: https://mccardle.io
twitter_username: robmccardle
github_username:  robmccardle
author: Rob McCardle
copyright: Rob McCardle

# Build settings
markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock', '*.sublime-*', 'lib','vendor', 'Rakefile', 's3_website.yml']
relative_permalinks: false
timezone: Europe/London
permalink: /:year/:month/:day/:title.html
gems:
    - jekyll-redirect-from
    - jekyll-feed
    - jekyll-sitemap
sass:
  style: compressed