# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rob McCardle. Creative Technology Director, Buckinghamshire UK
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Rob McCardle. Creative Technology Director, Buckinghamshire UK.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mccardle.io" # the base hostname & protocol for your site
twitter_username: robmccardle
github_username:  robmccardle

# Build settings
markdown: kramdown
